name: Perl-SAX
version: 0.05
abstract: Generate SAX events for Perl Documents
author: Adam Kennedy <cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  File::Spec: 0.80
  Test::More: 0.47
requires:
  perl: 5.005
  XML::SAX::Base: 1.04
  XML::SAX::Writer: 0.44
  PPI: 1.002
no_index:
  directory:
    - t.data
    - inc
generated_by: Module::Install version 0.36
