
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.62
distribution_type: module
version: 0.07
name: Perl-SAX
author: Adam Kennedy <cpan@ali.as>
license: perl
build_requires: 
  Test::More: 0.47
  File::Spec: 0.80
requires: 
  PPI: 1.002
  perl: 5.005
  XML::SAX::Writer: 0.44
  XML::SAX::Base: 1.04
abstract: Generate SAX events for perl source code (incomplete)
