# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Perl-SAX
version:      0.01
version_from: lib/Perl/SAX.pm
installdirs:  site
requires:
    Class::Autouse:                1.04
    File::Spec:                    0.83
    PPI:                           0.828
    Test::More:                    0
    XML::SAX::Base:                1.04
    XML::SAX::Writer:              0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
